=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Globale Herausforderungen des Klimawandels

Die Teilnehmenden kennen die globalen Herausforderungen des Klimawandels. Sie kennen den steigenden Energie- und Ressourcenbedarf der IT und deren wesentliche Treiber. Sie können erklären, wieso sich auch die IT mit dem Thema Ressourcen- und Energieeffizienz beschäftigen muss.

[[LZ-1-2]]
==== LZ 1-2: Möglichkeiten zur Einsparung von Energie durch Digitalisierung

Die Teilnehmenden kennen die Möglichkeiten zur Einsparung von Energie und CO~2~ durch die Digitalisierung. Sie kennen die Sektoren, die besonders von Digitalisierung profitieren. Der Unterschied zwischen Einsparungen in der IT und durch die IT ist bekannt.

[[LZ-1-3]]
==== LZ 1-3: Energieverbrauch von IT einordnen, beziffern und deren Treiber benennen

Die Teilnehmenden können den Energieverbrauch der Informationstechnik beziffern, können diesen in Relation zu anderen Sektoren einordnen und die wesentlichen Treiber benennen. Sie kennen Trends und Entwicklungen in der IT und zentrale Stellschrauben.

[[LZ-1-4]]
==== LZ 1-4: Basiskonzepte

Die Teilnehmenden können Begriffe wie Nachhaltigkeit, Energieeffizienz, negativer externer Effekt, CO~2~-Fußabdruck und -Handabdruck einordnen. Wichtige Kennzahlen und physikalische Einheiten wie CO~2~, CO~2~-Äquivalente, Watt, Joule und deren Bedeutung werden verstanden.

[[LZ-1-5]]
==== LZ 1-5: Handlungsfelder

Die Teilnehmenden kennen die Handlungsfelder zum Einsparen von CO~2~:

* Energieeffizienz - Verbrauche so wenig Energie wie möglich.
* Hardwareeffizienz - Beanspruche so wenig Hardware wie möglich.
* CO~2~-Emissionseffizienz - Verbrauche Energie möglichst dann und dort, wo sie am "grünsten" erzeugt wird.

// end::DE[]

// tag::EN[]
TODO
// end::EN[]
