=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Möglichkeiten zur Einsparung von Energie durch Digitalisierung

Die Teilnehmenden kennen die Möglichkeiten zur Einsparung von Energie und CO2 durch die Digitalisierung. Sie kennen die Sektoren, die besonders von Digitalisierung profitieren.

[[LZ-1-2]]
==== LZ 1-2: Energieverbrauch von IKT einordnen, beziffern und deren Treiber benennen

Die Teilnehmenden können den Energieverbrauch der Informations- und Kommunikationstechnik (IKT) beziffern, können diesen in Relation zu anderen Sektoren einordnen und die wesentlichen Treiber benennen. Sie kennen Trends und Entwicklungen in der IKT und zentrale Stellschrauben.

[[LZ-1-3]]
==== LZ 1-3: Basiskonzepte

Die Teilnehmenden können Begriffe wie Nachhaltigkeit, Energieeffizienz, negativer externer Effekt, CO2-Fußabdruck und -Handabdruck einordnen. Wichtige Kennzahlen und physikalische Einheiten wie CO2, CO2-Äquivalente, Watt, Joule und deren Bedeutung werden verstanden.

// end::DE[]

// tag::EN[]
[[LG-1-x]]
TODO

// end::EN[]
