= https://isaqb.org[iSAQB] Advanced Level Curriculum GREEN

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-green/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-green/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-green.svg["Contributors",link="https://github.com/isaqb-org/curriculum-green/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-green.svg["Issues",link="https://github.com/isaqb-org/curriculum-green/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-green.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-green/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains iSAQB Advanced Level curriculum *GREEN* in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue or a pull-request. Clone the repository, including the submodule:

+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-green.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-green.git --recursive
----
--

== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle, use the wrapper that comes with the repository: `./gradlew buildDocs`

This will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
  group 'Documentation'
  description 'Grouping task for generating all languages in several formats'
  dependsOn "renderDE", "renderEN"
}
----

In the task "renderDE", certain attributes (aka variables) are defined that configure the corresponding output.

== Maintainers

This repository is currently maintained by the curators of this currriculum. 
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
