=== {learning-goals}

// tag::DE[]

[[LZ-8-1]]
==== LZ 8-1: CI/CD-Strategien und deren Ressourcenbedarf kennen

Die Teilnehmenden kennen verschiedene Strategien des Infrastructure as Code, Continuous Integration und Continous Deployments. Dazu gehört, warum und wann diese üblicherweise eingesetzt werden, welchen grundsätzlichen Ressourcenbedarf diese haben können und wie sich Testausführung sowie Codeanalysen auf diesen Bedarf auswirken können.

[[LZ-8-2]]
==== LZ 8-2: Optimierung der CI/CD Prozesse durchführen

Die Teilnehmenden sind mit Strategien zur Ressourcenoptimierung und der Verringerung der CO~2~-Emissionen von CI/CD-Prozessen vertraut. Beispiele hierfür sind die Anwendung von Peak-Shaving, Time-Shifting und Location-Shifting. Sie können dazu Energieverbrauch und CO~2~-Emissionen der Ausführung von CI/CD-Pipelines bestimmen.

[[LZ-8-3]]
==== LZ 8-3: Optimierung der Infrastruktur vornehmen

Die Teilnehmenden kennen Verfahren zur Optimierung der Entwicklungs- und Deployment-Infrastruktur. Dazu zählen beispielsweise Betrachtung der tatsächlich notwenigen Resilienz, die Effizienzvorteile von Containern gegenüber virtuellen Maschinen, sowie der Einsatz von Caching für Build- und Testartefakte.

[[LZ-8-4]]
==== LZ 8-4: Teststrategie optimieren 

Die Teilnehmenden sind mit Möglichkeiten zur Verbesserung der Ressourceneffizienz ihrer Teststrategien und Testumgebungen vertraut. Dazu zählt beispielsweise die Wirkung verschiedener Testarten (Last-Test, Systemtest, Integrationstest, Unit-Test, ...) auf den Ressourcenverbrauch sowie die Verringerung dessen durch Test-Gap-Analysen und die bedarfsorientierte, zeitlich begrenzte Bereitstellung entsprechender Testumgebungen.

// end::DE[]

// tag::EN[]

[[LG-8-1]]
==== LG 8-1: Knowing CI/CD strategies and their resource requirements

Participants are familiar with various strategies of Infrastructure as Code, Continuous Integration and Continuous Deployments. This includes why and when these are usually used, what basic resource requirements they can have and how test execution and code analyses can affect these requirements.

[[LG-8-2]]
==== LG 8-2: Optimizing CI/CD processes

Participants are familiar with strategies for optimising resources and reducing CO~2~ emissions from CI/CD processes. Examples of this include the use of peak shaving, time shifting and location shifting. They can determine the energy consumption and CO~2~ emissions of executing CI/CD pipelines.

[[LG-8-3]]
==== LG 8-3: Optimising the infrastructure

Participants know methods for optimising the development and deployment infrastructure. This includes, for example, consideration of the actual resilience required, the efficiency advantages of containers over virtual machines and the use of caching for build and test artefacts.

[[LG-8-4]]
==== LG 8-4: Optimising the test strategy 

Participants are familiar with ways to improve the resource efficiency of their test strategies and test environments. This includes, for example, the effect of different test types (load test, system test, integration test, unit test, ...) on resource consumption and the reduction of this through test gap analyses and the demand-oriented, time-limited provision of appropriate test environments.

// end::EN[]

