=== {learning-goals}


// tag::DE[]
[[LZ-8-1]]
==== LZ 8-1: Cloud Antipatterns
Die Teilnehmenden kennen die Herausforderungen in der Cloud und typische Anti-Pattern wie z.B.

* Überprovisionierung durch fehlendes Monitoring oder fehlende Automatisierung in der Provisionierung
* TODO bitte ergänzen

[[LZ-8-2]]
==== LZ 8-2: Cloud Resource Provisioning
Die Teilnehmenden kennen einige Wege zur strukturierten Provisionierung von Cloud-Ressourcen wie z.B. Terraform, Crossplane oder Helm, wissen wie wichtig Automatisierung ist, um die Flexibilität von Cloud-Umgebungen nutzen zu können. Sie können dies konkret an Beispielen mit Bezug auf Ressourceneffizienz erläutern. Stichwort "Immutable Infrastructure".

[[LZ-8-3]]
==== LZ 8-3: Energie messen in der Cloud
Die Teilnehmenden können den Energieverbrauch in der Cloud schätzen und messen.

* TODO
* Footprint-Konsole üblicherweise nur mit Rolle Billing Account
* Oft keine absoluten Angaben
* Einschränkungen bei GCP, AWS und Azure nochmal anschauen
* unterschiedliche Services (Managed Dynamo DB vs. eigene VM) oft schwierig zu vergleichen
* Etsy Cloud Jewels

[[LZ-8-4]]
==== LZ 8-4: Kubernetes Optimierung
Die Teilnehmenden kennen Beispiele für Optimierungen von Kubernetes-Clustern
// end::DE[]

// tag::EN[]
[[LG-8-1]]
==== LG 8-1: TODO
TODO

[[LG-8-2]]
==== LG 8-2: TODO
TODO

[[LG-8-3]]
==== LG 8-3: TODO
TODO

[[LG-8-4]]
==== LG 8-4: TODO
TODO

// end::EN[]

