=== {learning-goals}


// tag::DE[]

[[LZ-8-1]]
==== LZ 8-1: CI/CD

Die Teilnehmenden kennen verschiedene Strategien des Infrastructure as Code, Continuous Integration und Continous Deployments. Dazu gehört, warum und wann diese üblicherweise eingesetzt werden, welchen grundsätzlichen Ressourcenbedarf diese haben können und wie sich Testausführung sowie Codeanalysen auf diesen Bedarf auswirken können.

[[LZ-8-2]]
==== LZ 8-2: Optimierung der CI/CD Prozesse

Die Teilnehmenden sind mit Methoden zur Ressourcenoptimierung von CI/CD-Prozessen vertraut. Beispiele hierfür sind die Anwendung von Peak-Shaving und Time-Shifting bei geplanten Builds, sowie das Deployment in räumlicher Nähe zur Zielgruppe im Kontext der Cloud.

[[LZ-8-3]]
==== LZ 8-3: Optimierung der Infrastruktur

Die Teilnehmenden kennen Verfahren zur Optimierung der Entwicklungs- und Deployment-Infrastruktur. Dazu zählen beispielsweise Betrachtung der tatsächlich notwenigen Resilienz, die Effizienzvorteile von Containern gegenüber virtuellen Maschinen, sowie der Einsatz von Caching für Build- und Testartefakte.

[[LZ-8-4]]
==== LZ 8-4: Optimierung der Teststrategie

Die Teilnehmenden sind mit Möglichkeiten zur Verbesserung der Ressourceneffizienz ihrer Teststrategien und Testumgebungen vertraut. Dazu zählt beispielsweise die Wirkung verschiedener Testarten (Last-Test, Systemtest, Integrationstest, Unit-Test, ...) auf den Ressourcenverbrauch sowie die Verringerung dessen durch Test-Gap-Analysen und die bedarfsorientierte, zeitlich begrenzte Bereitstellung entsprechender Testumgebungen.

// end::DE[]

// tag::EN[]
[[LG-8-1]]
==== LG 8-1: TODO
TODO

[[LG-8-2]]
==== LG 8-2: TODO
TODO

[[LG-8-3]]
==== LG 8-3: TODO
TODO

[[LG-8-4]]
==== LG 8-4: TODO
TODO

// end::EN[]

