=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Architekturstile und deren Bezug zu Energieeffizienz kennen und verstehen
Die Teilnehmenden können unterschiedliche Architekturstile wie beispielsweise verteilte Systeme, strukturierte Monolithen oder Serverless und deren Auswirkungen auf die Energieeffizienz einschätzen. Darüber hinaus sind sie in der Lage den Unterschied zwischen zustandslosen und zustandsbehafteten Komponenten hinsichtlich des Energiebedarfs einzuschätzen. Die Prinzipien von cloud-native Architekturen und ihre Auswirkungen auf die Energieeffizienz sind den Teilnehmenden bekannt.

[[LZ-6-2]]
==== LZ 6-2: Kommunikation und deren Auswirkungen auf Energieeffizienz kennen
Die Teilnehmenden kennen unterschiedliche Arten der Kommunikation (synchron versus asynchron) zwischen Bausteinen in Bezug auf die Bereitstellung von Daten sowie der verwendeten Formate und Protokolle (textbasierte versus binäre Protokolle) hinsichtlich der Energieeffizienz einschätzen. Sie sind in der Lage, den Einfluss von Datenkompression auf das übertragene Datenvolumen zu bewerten, und verstehen, dass eine Reduzierung der Aufrufhäufigkeit und des Datenvolumens sich positiv auf die Umweltbilanz auswirkt.

[[LZ-6-3]]
==== LZ 6-3: Datenbankmodelle und deren Eigenschaften in Bezug auf Energieeffizienz kennen
Die Teilnehmenden kennen unterschiedliche Arten von Datenbankmodellen (relational, NoSQL, etc.) und unterschiedliche Datenbanksysteme (PostgreSQL, DB2, Oracle, etc.) und können die richtige Auswahl unter dem Aspekt der Energieeffizienz treffen. Sie sind in der Lage ein geeignetes Service-Modell (self-hosting versus cloud-based managed service) für ihre Datenhaltung auszuwählen.

[[LZ-6-4]]
==== LZ 6-4: Spezifische Green IT Pattern kennen und anwenden 
Die Teilnehmenden kennen generell Muster wie beispielsweise die der Green Software Foundation, um die Energieeffizienz einer Architektur zu verbessern. Sie kennen die Web Sustainability Guidelines des W3C zur Energieeffizienz, die beim Webdesign berücksichtigt werden müssen. Sie sind mit Strategien wie Browser-Caching, der Verwendung eines CDN und Edge-Caching vertraut und in der Lage, diese in ihren Anwendungen zu implementieren. Sie kennen unterschiedliche Dateiformate und Arten von graphischen Elementen (z. B. Animationen) und sind in der Lage deren Energieeffizienz einzuschätzen.

// end::DE[]

// tag::EN[]

[[LG-6-1]]
==== LG 6-1: Knowing and understanding architectural styles and their relation to energy efficiency
Participants can assess different architectural styles such as distributed systems, structured monoliths or serverless and their impact on energy efficiency. In addition, they are able to assess the difference between stateless and stateful components in terms of energy requirements. Participants are familiar with the principles of cloud-native architectures and their impact on energy efficiency.

[[LG-6-2]]
==== LG 6-2: Knowing communication and its impact on energy efficiency
Participants are familiar with different types of communication (synchronous versus asynchronous) between building blocks in relation to the provision of data, and can assess the formats and protocols used (text-based versus binary protocols) in terms of energy efficiency. They are able to evaluate the influence of data compression on the transmitted data volume and understand that reducing the call frequency and data volume has a positive effect on the environmental balance.

[[LG-6-3]]
==== LG 6-3: Knowing database models and their characteristics in relation to energy efficiency
Participants are familiar with different types of database models (relational, NoSQL, etc.) and different database systems (Postgres, DB2, Oracle, etc.) and can make the right choice in terms of energy efficiency. They are able to select a suitable service model (self-hosting versus cloud-based managed service) for their data storage.

[[LG-6-4]]
==== LG 6-4: Knowing and applying specific Green IT patterns 
Participants are generally familiar with patterns such as those of the Green Software Foundation to improve the energy efficiency of an architecture. They are knowledgeable with the W3C's Web Sustainability Guidelines on energy efficiency, which must be taken into account in web design. They are familiar with strategies such as browser caching, the use of a CDN and edge caching, and are able to implement these in their applications. They are familiar with different file formats and types of graphic elements (e.g. animations) and are able to assess their energy efficiency.

// end::EN[]

