=== {learning-goals}


// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Architekturstile und Energieeffizienz
Die Teilnehmenden können unterschiedliche Architekturstile und deren Auswirkungen auf die Energieeffizienz einschätzen.

* Stateless
* Microservices
* (strukturierter) Monolith
* Serverless

[[LZ-6-2]]
==== LZ 6-2: Kommunikation und Energieeffizienz
Die Teilnehmenden kennen unterschiedliche Arten der Kommunikation zwischen Bausteinen in Bezug auf die Bereitstellung von Daten sowie der verwendeten Formate und Protokolle hinsichtlich der Energieeffizienz einschätzen.

* Datenkompression
* Verwendung von Binärprotokollen
* Reduzierung von Aufrufhäufigkeit und Datenvolumen
* Synchrone versus asynchrone Kommunikation

[[LZ-6-3]]
==== LZ 6-3: Datenbanken und Energieeffizienz
Die Teilnehmenden kennen unterschiedliche Arten von Datenbankmodellen (relational, NoSQL, etc.) und sind in der Lage Optimierungspotentiale bei Datenbanken zu identifizieren.

[[LZ-6-4]]
==== LZ 6-4: Spezifische Green IT Pattern
Die Teilnehmenden können die Patterns "Time Shifting" und "Peak Shaving" in Bezug auf deren Energieeffizienz bewerten und sind in der Lage diese in einem realen System einzusetzen.

[[LZ-6-5]]
==== LZ 6-5: Web Sustainability Guidelines
Die Teilnehmenden kennen die Vorschläge des W3C Energieeffizienz beim Web Design zu berücksichtigen sind in der Lage diese in ihren Anwendungen umzusetzen.

* Browser Caching
* Einsatz von CDN und Edge Caching
* Dateiformate und graphische Elemente (Animationen)

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: TODO
TODO

[[LG-6-2]]
==== LG 6-2: TODO
TODO

[[LG-6-3]]
==== LG 6-3: TODO
TODO

[[LG-6-4]]
==== LG 6-4: TODO
TODO
// end::EN[]

