=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Architekturstile und deren Bezug zu Energieeffizienz kennen und verstehen
Die Teilnehmenden können unterschiedliche Architekturstile wie beispielsweise verteilte Systeme, strukturierte Monolithen oder Serverless und deren Auswirkungen auf die Energieeffizienz einschätzen. Darüber hinaus sind sie in der Lage den Unterschied zwischen zustandslosen und zustandsbehafteten Komponenten hinsichtlich des Energiebedarfs einzuschätzen. Die Prinzipien von cloud-native Architekturen und ihre Auswirkungen auf die Energieeffizienz sind den Teilnehmenden bekannt.

[[LZ-6-2]]
==== LZ 6-2: Kommunikation und deren Auswirkungen auf Energieeffizienz kennen
Die Teilnehmenden kennen unterschiedliche Arten der Kommunikation (synchron versus asynchron) zwischen Bausteinen in Bezug auf die Bereitstellung von Daten sowie der verwendeten Formate und Protokolle (textbasierte versus binäre Protokolle) hinsichtlich der Energieeffizienz einschätzen. Sie sind in der Lage den Einfluss von Datenkompression auf das übertragenen Datenvolumen zu bewerten und wissen, dass die Energieeffizienz durch eine Reduzierung von Aufrufhäufigkeit und des Datenvolumens positiv beeinflusst wird.

[[LZ-6-3]]
==== LZ 6-3: Datenbanken und deren Eigenschaften im Bezug auf Energieeffizienz kennen
Die Teilnehmenden kennen unterschiedliche Arten von Datenbankmodellen (relational, NoSQL, etc.) und unterschiedliche Datenbanksysteme (Postgres, DB2, Oracle, etc.) und können die richtige Auswahl unter dem Aspekt der Energieeffizienz treffen. Sie sind in der Lage ein geeignetes Service-Modell (self-hosting versus cloud-based managed service) für ihre Datenhaltung auszuwählen.

[[LZ-6-4]]
==== LZ 6-4: Spezifische Green IT Pattern kennen und anwenden 
Die Teilnehmenden kennen generell Muster wie beispielsweise die der Green Software Foundation, um die Energieeffizienz einer Architektur zu verbessern. Darüber hinaus sind sich die Teilnehmenden bewusst, dass man eine Reduzierung des CO~2~-Bedarfs durch die Verwendung von mehr erneuerbarer Energie oder durch eine Verringerung des Ressourcenbedarfs erzielen kann. Sie wissen, dass durch die Anwendung von Time- und Location Shifting der Anteil von grüner Energie erhöht werden kann, während andere Muster, wie beispielsweise Peak Shaving, den Ressourcenbedarf verringern.

[[LZ-6-5]]
==== LZ 6-5: Web Sustainability Guidelines kennen und einsetzen
Die Teilnehmenden kennen die Vorschläge des W3C Energieeffizienz, die beim Web Design zu berücksichtigen sind, wie beispielsweise Browser Caching, Einsatz eines CDNs, Edge Caching und sind in der Lage diese in ihren Anwendungen umzusetzen. Sie kennen unterschiedliche Dateiformate und Arten von graphischen Elementen (z. B. Animationen) und sind in der Lage deren Energieeffizienz einzuschätzen.

// end::DE[]

// tag::EN[]

[[LG-6-1]]
==== LG 6-1: Know and understand architectural styles and their relation to energy efficiency
Participants can assess different architectural styles such as distributed systems, structured monoliths or serverless and their impact on energy efficiency. In addition, they are able to assess the difference between stateless and stateful components in terms of energy requirements. Participants are familiar with the principles of cloud-native architectures and their impact on energy efficiency.

[[LG-6-2]]
==== LG 6-2: Knowing communication and its impact on energy efficiency
Participants are familiar with different types of communication (synchronous versus asynchronous) between building blocks in relation to the provision of data and the formats and protocols used (text-based versus binary protocols) with regard to energy efficiency. They are able to evaluate the influence of data compression on the transferred data volume and know that energy efficiency is positively influenced by a reduction in call frequency and data volume.

[[LG-6-3]]
==== LG 6-3: Know databases and their properties in relation to energy efficiency
Participants are familiar with different types of database models (relational, NoSQL, etc.) and different database systems (Postgres, DB2, Oracle, etc.) and can make the right choice in terms of energy efficiency. They are able to select a suitable service model (self-hosting versus cloud-based managed service) for their data storage.

[[LG-6-4]]
==== LG 6-4: Know and apply specific Green IT patterns 
Participants are generally familiar with patterns such as those of the Green Software Foundation to improve the energy efficiency of an architecture. In addition, the participants are aware that a reduction in CO~2~ requirements can be achieved by using more renewable energy or by reducing resource requirements. They know that by applying time and location shifting, the proportion of green energy can be increased while other patterns, such as peak shaving, reduce resource requirements.

[[LG-6-5]]
==== LG 6-5: Know and use Web Sustainability Guidelines
Participants are familiar with the W3C energy efficiency proposals to be considered in web design, such as browser caching, use of a CDN, edge caching and are able to implement these in their applications. They are familiar with different file formats and types of graphic elements (e.g. animations) and are able to assess their energy efficiency.

// end::EN[]

