=== {learning-goals}
Das Ziel dieses Kapitels ist es, dass die Teilnehmenden ihre bereits erworbenen Kenntnisse in Bezug auf Qualitätsanforderungen und unterschiedlichen Messverfahren beim Architekturentwurf berücksichtigen.

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Architekturstile und Energieeffizienz
Die Teilnehmenden können unterschiedliche Architekturstile wie beispielsweise verteilte Systeme, strukturierte Monolithen oder Serverless und deren Auswirkungen auf die Energieeffizienz einschätzen. Darüber hinaus sind sie in der Lage den Unterschied zwischen zustandslosen und zustandsbehafteten Komponenten hinsichtlich des Energiebedarfs einzuschätzen. Die Prinzipien von cloud-native Architekturen und ihre Auswirkungen auf die Energieeffizienz sind den Teilnehmenden bekannt.

[[LZ-6-2]]
==== LZ 6-2: Kommunikation und Energieeffizienz
Die Teilnehmenden kennen unterschiedliche Arten der Kommunikation (synchron versus asynchron) zwischen Bausteinen in Bezug auf die Bereitstellung von Daten sowie der verwendeten Formate und Protokolle (textbasierte versus binäre Protokolle) hinsichtlich der Energieeffizienz einschätzen. Sie sind in der Lage den Einfluss von Datenkompression auf das übertragenen Datenvolumen zu bewerten und wissen, dass die Energieeffizienz durch eine Reduzierung von Aufrufhäufigkeit und des Datenvolumens positiv beeinflusst wird.

[[LZ-6-3]]
==== LZ 6-3: Datenbanken und Energieeffizienz
Die Teilnehmenden kennen unterschiedliche Arten von Datenbankmodellen (relational, NoSQL, etc.) und unterschiedliche Datenbanksysteme (Postgres, DB2, Oracle, etc.) und können die richtige Auswahl unter dem Aspekt der Energieeffizienz treffen. Sie sind in der Lage ein geeignetes Service-Modell (self-hosting versus cloud-based managed service) für ihre Datenhaltung auszuwählen.

[[LZ-6-4]]
==== LZ 6-4: Spezifische Green IT Pattern
Die Teilnehmenden kennen generell Muster wie beispielsweise die der Green Software Foundation, um die Energieeffizienz einer Architektur zu verbessern. Darüber hinaus sind sich die Teilnehmenden bewusst, dass man eine Reduzierung des CO~2~-Bedarfs durch die Verwendung von mehr erneuerbarer Energie oder durch eine Verringerung des Ressourcenbedarfs erzielen kann. Sie wissen, dass durch die Anwendung von Time- und Location Shifting der Anteil von grüner Energie erhöht werden kann während ander Muster wie beispielsweise Peak Shaving den Ressourcenbedarf verringert. Die Teilnehmenden sind in der Lage unterschiedliche Pattern beim Architekturentwurf zu berücksichtigen.

[[LZ-6-5]]
==== LZ 6-5: Web Sustainability Guidelines
Die Teilnehmenden kennen die Vorschläge des W3C Energieeffizienz, die beim Web Design zu berücksichtigen sind, wie beispielsweise Browser Caching, Einsatz eines CDNs, Edge Caching und sind in der Lage diese in ihren Anwendungen umzusetzen. Sie kennen unterschiedliche Dateiformate und Arten von graphische Elemente (Animationen) und sind in der Lage deren Energieeffizienz einzuschätzen.

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: TODO
TODO

[[LG-6-2]]
==== LG 6-2: TODO
TODO

[[LG-6-3]]
==== LG 6-3: TODO
TODO

[[LG-6-4]]
==== LG 6-4: TODO
TODO
// end::EN[]

