=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Energieeffizienz eines Rechenzentrums einschätzen
Die Teilnehmenden können die Energieeffizienz eines Rechenzentrums einschätzen (R1)

[[LZ-4-2]]
==== LZ 4-2: Leistung-Last-Beziehung von Hardware
Die Teilnehmenden kennen die Leistung-Last-Beziehung von Hardware.

[[LZ-4-3]]
==== LZ 4-3: Server Idle Energy Coefficient berechnen und einschätzen
Die Teilnehmenden können den Server Idle Energy Coefficient berechnen und einschätzen.

[[LZ-4-4]]
==== LZ 4-4: Ressourcen in Relation zur erbrachten Leistung  bringen
Die Teilnehmenden sind in der Lage, Ressourcen in Relation zur erbrachten Leistung zu bringen
(Business-Metrik).

[[LZ-4-5]]
==== LZ 4-5: Verschiedene Kategorien von Messverfahren kennen
Die Teilnehmenden kennen verschiedene Kategorien von Messverfahren und kennen deren Vor- und
Nachteile.

[[LZ-4-6]]
==== LZ 4-6: Metrik Software Carbon Intensity
Die Teilnehmenden kennen die Idee hinter der Metrik Software Carbon Intensity.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: TBD
tbd.

[[LG-4-2]]
==== LG 4-2: TBD
tbd.
// end::EN[]

