=== {learning-goals}

// tag::DE[]

[[LZ-4-1]]
==== LZ 4-1: Energieeffizienz eines Rechenzentrums einschätzen
Die Teilnehmenden können die Energieeffizienz eines Rechenzentrums einschätzen. Sie kennen den Power Usage Effectivness (PUE) und seine Vor- und Nachteile

[[LZ-4-2]]
==== LZ 4-2: Server Idle Energy Coefficient berechnen und einschätzen
Die Teilnehmenden kennen die Leistung-Last-Beziehung von Hardware. Sie können den Server Idle Energy Coefficient (SIEC) berechnen und einschätzen.

[[LZ-4-2]]
==== LZ 4-2: Ressourcen in Relation zur erbrachten Leistung  bringen
Die Teilnehmenden sind in der Lage, Ressourcen in Relation zur erbrachten Leistung zu bringen
(Business-Metrik).

[[LZ-4-4]]
==== LZ 4-6: Metrik Software Carbon Intensity
Die Teilnehmenden kennen die Idee hinter der Metrik Software Carbon Intensity (SCI).

[[LZ-4-5]]
==== LZ 4-5: Verschiedene Kategorien von Messverfahren kennen
Die Teilnehmenden kennen verschiedene Kategorien von Messverfahren und kennen deren Vor- und
Nachteile.
Die wichtigsten Kategorien sind TODO (Cloud, Fullstack, programmiersprachenspezifisch, etc.)

[[LZ-4-6]]
==== LZ 4-6: Messwerkzeuge
Die Teilnehmenden kennen Werkzeuge aus jeder Kategorie der Messverfahren (sie sollen einen Überblick haben. Sie müssen nicht zu jedem Werkzeug DEtails kenne, insbesondere nicht im praktischen Teil ausprobieren)

[[LZ-4-7]]
==== LZ 4-7: Messmethodik
Die Teilnehmenden kennen das methodische Vorgehen beim Messen des Energieverbrauchs, bzw. der CO~2~-Intensität. Sie verstehen, dass die Bewertung / Messung des absoluten Verbrauchs schwierig ist. Sie verstehen, dass eine Messung und Bewertung der Trends die zielführendere Maßnahme ist.

Sie kennen Proxy-Metriken für die CO~2~-Intensität (Stromverbrauch).



// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: TBD
tbd.

[[LG-4-2]]
==== LG 4-2: TBD
tbd.
// end::EN[]

