// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Galt die IT lange Zeit als Lösung vieler Probleme, die in Zusammenhang mit dem Klimawandel stehen, ist sie mittlerweile selbst Gegenstand von Optimierungsbetrachtungen geworden. Ineffiziente Programmierung, oft hervorgerufen durch die Notwendigkeit eines schnellen Time-to-market, wurde vielfach durch immer schnellere Hardware oder mehr Ressourcen in der Cloud kompensiert. Diesen Weg gilt es zu verlassen. Die CO~2~-Emissionen, die durch Software entstehen, müssen konsequent reduziert werden.

Im Modul {curriculum-short} lernen die Teilnehmenden, das Thema Green Software ganzheitlich zu betrachten. Dies beginnt mit der Betrachtung der Rolle der IT beim Aufhalten des Klimawandels, einer Einführung in die aktuelle Regulatorik, die Sicht auf die Anforderungen verschiedener Stakeholder und der Benennung von Handlungsfeldern in Unternehmen. Von dort geht es über das Messen und das Monitoring von CO~2~-Emissionen bzw. Energieverbrauch hin zum Kernthema der Softwareentwicklung. In dieses zentrale Themengebiet fällt die Energieeffizienz verschiedener Softwarearchitekturen sowie grundlegender verwendeter Konzepte, energieeffizientes Datenhandling, optimierte Algorithmen aber auch der Einfluss und das Management von Qualitätsanforderungen in Bezug auf Energieeffizienz. Ein weiterer wichtiger Bestandteil ist das Thema Cloud, sowohl bezüglich Auswahl des Providers als auch den Möglichkeiten zum CO~2~-armen Betrieb darin. Zuletzt finden Möglichkeiten zur Verbesserung der Energieeffizienz im Entwicklungsprozess Betrachtung.

Am Ende des Moduls {curriculum-short} kennen die Teilnehmenden die wesentlichen Hebel um CO~2~ in der IT zu reduzieren. Sie können einschätzen, welche Auswirkungen die Softwarearchitektur dabei hat und wie Architekturmuster- und -stile wirken. Sie kennen Fallstricke beim Datenhandling und können einschätzen, welche Auswirkungen die Auswahl von technischen Komponenten haben. In Bezug auf die Cloud wissen die Teilnehmenden die dort angebotenen Möglichkeiten im Sinne der Energieeffizienz nutzen zu können.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module presents {curriculum-short} to the participants …
At the end of the module, the participants know … and are able to …
TODO
// end::EN[]

