// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Galt die IT lange Zeit als Lösung vieler Probleme, die in Zusammenhang mit dem Klimawandel stehen, ist sie mittlerweile selbst Gegenstand von Optimierungsbetrachtungen geworden. Ineffiziente Programmierung, oft hervorgerufen durch die Notwendigkeit eines schnellen Time-to-market, wurde vielfach durch immer schnellere Hardware oder mehr Ressourcen in der Cloud kompensiert. Diesen Weg gilt es zu verlassen. Die CO~2~-Emissionen, die durch Software entstehen, müssen konsequent reduziert werden.

Im Modul {curriculum-short} lernen die Teilnehmenden, das Thema Green Software ganzheitlich zu betrachten. Dies beginnt mit der Betrachtung der Rolle der IT beim Aufhalten des Klimawandels, einer Einführung in die aktuelle Regulatorik, die Sicht auf die Anforderungen verschiedener Stakeholder und der Benennung von Handlungsfeldern in Unternehmen. Von dort geht es über das Messen und das Monitoring von CO~2~-Emissionen bzw. Energieverbrauch hin zum Kernthema der Softwareentwicklung. In dieses zentrale Themengebiet fällt die Energieeffizienz verschiedener Softwarearchitekturen sowie grundlegender verwendeter Konzepte, energieeffizientes Datenhandling, optimierte Algorithmen aber auch der Einfluss und das Management von Qualitätsanforderungen in Bezug auf Energieeffizienz. Ein weiterer wichtiger Bestandteil ist das Thema Cloud, sowohl bezüglich Auswahl des Providers als auch den Möglichkeiten zum CO~2~-armen Betrieb darin. Zuletzt finden Optionen zur Verbesserung der Energieeffizienz im Entwicklungsprozess Betrachtung.

Am Ende des Moduls {curriculum-short} kennen die Teilnehmenden die wesentlichen Hebel, um CO~2~ in der IT zu reduzieren. Sie können einschätzen, welche Auswirkungen die Softwarearchitektur hat und wie Architekturmuster- und -stile wirken. Sie kennen Fallstricke beim Datenhandling und können einschätzen, welche Auswirkungen die Auswahl von technischen Komponenten haben. In Bezug auf die Cloud wissen die Teilnehmenden die dort angebotenen Möglichkeiten im Sinne der Energieeffizienz einzusetzen.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

While IT was long seen as the solution to many problems associated with climate change, it has now itself become the subject of optimisation considerations. Inefficient programming, often caused by the need for a fast time-to-market, has often been compensated for by ever faster hardware or more resources in the cloud. This path must be abandoned. The CO~2~ emissions caused by software must be consistently reduced.

In the {curriculum-short} module, participants learn to take a holistic view of the topic of green software. This begins with an examination of the role of IT in halting climate change, an introduction to current regulations, a view of the requirements of various stakeholders and the identification of fields of action in companies. From there, we move on to measuring and monitoring CO~2~ emissions and energy consumption and on to the core topic of software development. This central topic area includes the energy efficiency of various software architectures and basic concepts used, energy-efficient data handling, optimised algorithms and also the influence and management of quality requirements in relation to energy efficiency. Another important component is the topic of the cloud, both in terms of provider selection and the possibilities for low-CO~2~ operation. Finally, options for improving energy efficiency in the development process are considered.

At the end of the module {curriculum-short}, participants will know the key levers for reducing CO~2~ in IT. They will be able to assess the impact of software architecture and how architecture patterns and styles work. They know the pitfalls of data handling and can assess the impact of the selection of technical components. With regard to the cloud, participants know how to utilise the options offered there in terms of energy efficiency.

// end::EN[]

