=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Programmiersprachen und Energieeffizienz
Die Teilnehmenden kennen verschiedene Programmiersprachen und deren Energieeffizienz.

[[LZ-5-2]]
==== LZ 5-2: Ahead-of-Time und Just-in-Time
Die Teilnehmenden verstehen die Unterschiede zwischen Ahead-of-Time und Just-in-Time Kompilierung und deren Implikationen.

[[LZ-5-3]]
==== LZ 5-3: Garbage-Collection
Die Teilnehmenden kennen die Zielkonflikte von Garbage-Collectoren.

[[LZ-5-4]]
==== LZ 5-4: Rechnerische Komplexität und Energieeffizienz
Die Teilnehmenden kennen die rechnerische Komplexität und können daraus Schlüsse zur Energieeffizienz ziehen.

[[LZ-5-5]]
==== LZ 5-5: Datenstrukturen / Operationen und Energieeffizienz
Die Teilnehmenden können Datenstrukturen und Operationen darauf bezüglich Energieeffizienz einschätzen.

[[LZ-5-6]]
==== LZ 5-6: Caching und Energieeffizienz
Die Teilnehmenden können Caching in Verbindung mit Energieeffizienz einsetzen.

[[LZ-5-7]]
==== LZ 5-7: Beispiele für Optimierungen
Die Teilnehmenden kennen Beispiele für Optimierungen auf Ebene der Programmiersprache.


// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: TODO
TODO

[[LG-5-2]]
==== LG 5-2: TODO
TODO

[[LG-5-3]]
==== LG 5-3: TODO
TODO

[[LG-5-4]]
==== LG 5-4: TODO
TODO

[[LG-5-5]]
==== LG 5-5: TODO
TODO

[[LG-5-6]]
==== LG 5-6: TODO
TODO

[[LG-5-7]]
==== LG 5-7: TODO
TODO
// end::EN[]

